### ISSUE TITLE
Initial server setup and database connection using mongoose

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#1]
using Express locally host your server and using mongoose to connect to mongoDB shell or Atlas

**Comment by akshatshukla13** [comment]
I’d like to contribute to this issue!

**Comment by Avinash-Baraiya** [comment]
I'm interested. I'll set up Express with MongoDB (local & Atlas) using Mongoose

**Comment by devangsvaghani** [comment]
> I'm interested. I'll set up Express with MongoDB (local & Atlas) using Mongoose

Okay, I am assigning this issue to you.
