### ISSUE TITLE
create an API  to Randomly pick a word form the list of words provided (random_words) and send to the user.

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#12]
use `fs` to access the file and randomly select a word. The words are in ascending order make sure to shuffle them before selecting.

**Comment by JaySabva** [comment]
I would like to take this!

**Comment by vashishtpurani** [comment]
Also keep track of the word sent in the backend | you can store it in the database or use session this can be enhanced upon later when dealing with socket

**Comment by Avinash-Baraiya** [comment]
I am also interested.

**Comment by vashishtpurani** [comment]
@Avinash-Baraiya I'm assigning you this issue do your best!!

**Comment by Shayan12456** [comment]
may i do it?

**Comment by theromanhinds** [comment]
Hi, I'm a CS student. I'd like to complete this issue for a course I'm taking. Could you please explain where I can find the list of words?

**Comment by theromanhinds** [comment]
Here is my attempt at the issue. Please let me know if there are any changes I should make.

https://github.com/MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs/pull/21
