### ISSUE TITLE
Create a middleware to authenticate the user after otp-verification

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#13]
Use JWT to verify that the user is on the same device which he used to authenticate the OTP(send a JWT in RES and expect the same when the user tries to access the sign-up API).

**Comment by JaySabva** [comment]
I would like to take this.

**Comment by JaySabva** [comment]
i have some doubt regarding the use of the OTP.

**Comment by devangsvaghani** [comment]
@JaySabva you are assigned this issue.
