### ISSUE TITLE
Create a middleware to authenticate user after login.

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#14]
After the user has successfully logged in send a JWT in response and expect the JWT in the payload when the user tries to access any functionality down the line.

**Comment by harit1412** [comment]
Please assign this issue to me I would like to work on it , ( I had worked on login controllers , so this can be easier for me )

**Comment by vashishtpurani** [comment]
@harit1412 I'm assigning you this issue do your best

**Comment by JaySabva** [comment]
@vashishtpurani 
this task is of frontend right?

**Comment by JaySabva** [comment]
@harit1412 i have created a jwt class in utils folder so use from there. (Jwt.verify(token)) as middleware.

**Comment by Rajyalakshmi41** [comment]
Please assign this issue to me.
