### ISSUE TITLE
Setup socket.io in the server

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#16]

**Comment by dheerajsingh01** [comment]
hey @vashishtpurani  can you assign this issue to me

**Comment by dheerajsingh01** [comment]
And if you want to add description you can add it .

**Comment by pdishant5** [comment]
I would like to work on this issue.

**Comment by Avinash-Baraiya** [comment]
@vashishtpurani  please assign me this issue i want to do this.

**Comment by dheerajsingh01** [comment]
Is this issue fixed or not , if not then i can fix it now.

**Comment by theromanhinds** [comment]
Hi, I'm a CS student. I'd like to complete this issue for a course I'm taking. 

@devangsvaghani Could you please clarify what you'd like to be implemented besides adding the socket.io dependency and the code to start the server?

**Comment by theromanhinds** [comment]
I believe I've initialized the server. Please let me know if there is something else you'd like.

https://github.com/MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs/pull/20

**Comment by NidhiDodiya1014** [comment]
@Avinash-Baraiya you have been assigned this issue 2 days ago. would you like to solve it? or should we assign it to others?

**Comment by Avinash-Baraiya** [comment]
I will be done till 6 pm
