### ISSUE TITLE
Create a model/schema for OTP verification(variables are provided in the description) and make an API for sending an OTP and OTP verification

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#2]
Schema for OTP
{
"Email":"",
"OTP":""
}
You can use otp-generator library for generation of otp : https://www.npmjs.com/package/otp-generator
the otp does not need to be sent to an email you can simply console log.

It is preferable to use Postman for API testing.

**Comment by harit1412** [comment]
will there be any expiry time for OTP , like after 2 minutes even right OTP will not be considered ?

**Comment by JaySabva** [comment]
i would like to contribute.

**Comment by NidhiDodiya1014** [comment]
> will there be any expiry time for OTP , like after 2 minutes even right OTP will not be considered ?

yes! if you can do that...that will be added to your points.

**Comment by devangsvaghani** [comment]
This issue is assigned to @JaySabva .
