### ISSUE TITLE
After OTP verification create APIs for User Signup and Login.

### ISSUE THREAD

**Issue by vashishtpurani** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#3]
Schema for UserSignup/Login:
{
"userName:":"",
"email":"",
"password":""
}
Brownie points if you encrypt the password

**Comment by JaySabva** [comment]
i would like to take this task.

**Comment by harit1412** [comment]
I like to contribute to this issue , Please assign it to me

**Comment by devangsvaghani** [comment]
> I like to contribute to this issue , Please assign it to me

This issue is assigned to you.

**Comment by AnujKshatriya** [comment]
hello @devangsvaghani I would like to work on this issue, can I proceed?

**Comment by devangsvaghani** [comment]
> hello @devangsvaghani I would like to work on this issue, can I proceed?

This issue is already assigned, we are working on adding new issues.
