### ISSUE TITLE
Implement Email Sending Functionality for OTP Generation

### ISSUE THREAD

**Issue by Brinda-Sorathiya** [MSTC-DA-IICT/Hacktoberfest24-Wordle-Game-Nodejs#8]
Currently, the OTP is generated and saved in the database, but there is no functionality to send the OTP to the user's email. We need to implement the functionality that sends the OTP to the user's email when it is generated.

Backend Tasks:
-->Install Nodemailer:
     - Use nodemailer or another email-sending library to handle sending emails.
     - You can install nodemailer using the following command:
           npm install nodemailer

-->Set Up Email Transporter:
      -Configure an email transporter using an email service like Gmail, SendGrid, or SMTP in your .env file.
      -Example for Gmail:
          const nodemailer = require('nodemailer');
          const transporter = nodemailer.createTransport({
          service: 'gmail',
            auth: {
              user: process.env.EMAIL_USER,  // Email from environment variable
              pass: process.env.EMAIL_PASS   // Password from environment variable
          }
        });

-->Send Email After OTP Generation:
       -Modify the requestOtp function in controllers/login_controll.js to send an email with the OTP after it is generated.
       -You can refer to resources available on internet to do this.

-->Update requestOtp Function:
      -After generating and saving the OTP in the database, call the sendOtpEmail function to send the OTP to the user’s email.

**Comment by JaySabva** [comment]
@Brinda-Sorathiya i would like to take this.

**Comment by AnujKshatriya** [comment]
@Brinda-Sorathiya can you assign this issue to me? I would like to work on it

**Comment by Shayan12456** [comment]
@Brinda-Sorathiya 
I am working on it!

**Comment by harit1412** [comment]
@Brinda-Sorathiya  I would like to work on this issue

**Comment by JaySabva** [comment]
i have completed this 🗿

**Comment by devangsvaghani** [comment]
Since @JaySabva already solved this issue, so make a pull request for this

Everyone else, Tomorrow new issues will be added so kindly wait for that
